apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paas-dev-porter.fullname" . }}
  labels:
    {{- include "paas-dev-porter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "paas-dev-porter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "paas-dev-porter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "paas-dev-porter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: [ "/bin/sh" ]
          args: [ "-c", "air -c .air.toml" ]
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env  }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: github-app-pem
            mountPath: "/porter/.cred/github_app_private_key.pem"
            subPath: github_app_private_key.pem
            readOnly: true
          - name: gcr-key-file
            mountPath: "/porter/.cred/gcr-key.json"
            readOnly: true
            subPath: gcr-key.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: github-app-pem
        secret:
          secretName: github-app-private-key
      - name: gcr-key-file
        secret:
          secretName: gcr-key-file
